#!/bin/bash
#
# setup_cron.sh - Setup cron jobs for AI Employee watchers
#
# Usage: ./setup_cron.sh [--remove] [--dry-run]
#
# Options:
#   --remove    Remove existing cron entries instead of adding
#   --dry-run   Show what would be added/removed without making changes
#

set -e

# Configuration
VAULT_PATH="/mnt/d/personal-ai-employee"
PYTHON_CMD="python3"
LOG_DIR="$VAULT_PATH/Logs"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# Get absolute path to watchers
WATCHERS_DIR="$VAULT_PATH/watchers"

# Cron entries for Silver Tier
# Format: minute hour day month weekday command
CRON_ENTRIES=(
    # Gmail watcher - every 2 minutes
    "*/2 * * * * cd $VAULT_PATH && $PYTHON_CMD $WATCHERS_DIR/gmail_watcher.py --once >> $LOG_DIR/cron_gmail.log 2>&1"
    
    # WhatsApp watcher - every 5 minutes
    "*/5 * * * * cd $VAULT_PATH && $PYTHON_CMD $WATCHERS_DIR/whatsapp_watcher.py --once >> $LOG_DIR/cron_whatsapp.log 2>&1"
    
    # LinkedIn watcher - every 15 minutes
    "*/15 * * * * cd $VAULT_PATH && $PYTHON_CMD $WATCHERS_DIR/linkedin_watcher.py --once >> $LOG_DIR/cron_linkedin.log 2>&1"
    
    # Reasoning loop - every 10 minutes
    "*/10 * * * * cd $VAULT_PATH && claude --print \"Use ReasoningLoop to process all pending tasks in Needs_Action\" >> $LOG_DIR/cron_reasoning.log 2>&1"
    
    # LinkedIn post scheduler - Mon/Wed/Fri at 9 AM
    "0 9 * * 1,3,5 cd $VAULT_PATH && claude --print \"Use LinkedInAutoPost to draft and schedule today's LinkedIn post\" >> $LOG_DIR/cron_linkedin_post.log 2>&1"
    
    # Dashboard refresh - every hour
    "0 * * * * cd $VAULT_PATH && claude --print \"Refresh Dashboard.md with latest stats\" >> $LOG_DIR/cron_dashboard.log 2>&1"
    
    # Approval expiry check - every 6 hours
    "0 */6 * * * cd $VAULT_PATH && claude --print \"Use HumanApprovalRequest to expire pending approvals older than 24 hours\" >> $LOG_DIR/cron_approval.log 2>&1"
    
    # Orchestrator - every minute (processes approved files)
    "* * * * * cd $VAULT_PATH && $PYTHON_CMD $WATCHERS_DIR/orchestrator.py --once >> $LOG_DIR/cron_orchestrator.log 2>&1"
    
    # Daily log rotation - midnight
    "0 0 * * * find $LOG_DIR -name \"*.log\" -mtime +7 -delete >> /dev/null 2>&1"
)

# Display usage
usage() {
    echo "Usage: $0 [--remove] [--dry-run]"
    echo ""
    echo "Options:"
    echo "  --remove    Remove existing cron entries instead of adding"
    echo "  --dry-run   Show what would be added/removed without making changes"
    echo "  --help      Show this help message"
    exit 0
}

# Parse arguments
REMOVE=false
DRY_RUN=false

for arg in "$@"; do
    case $arg in
        --remove)
            REMOVE=true
            ;;
        --dry-run)
            DRY_RUN=true
            ;;
        --help)
            usage
            ;;
        *)
            echo "Unknown option: $arg"
            usage
            ;;
    esac
done

# Detect OS and set appropriate crontab command
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    CRONTAB_CMD="crontab"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    CRONTAB_CMD="crontab"
else
    echo "Warning: Unknown OS, assuming crontab is available"
fi

# Check if crontab is available
if ! command -v $CRONTAB_CMD &> /dev/null; then
    echo "Error: crontab command not found!"
    echo ""
    echo "Please install cron daemon:"
    echo "  Ubuntu/Debian: sudo apt-get install cron"
    echo "  macOS: cron is pre-installed"
    echo "  Windows: Use Task Scheduler instead (see README.md)"
    exit 1
fi

# Get current crontab
CURRENT_CRONTAB=$($CRONTAB_CMD -l 2>/dev/null || echo "")

# Generate new crontab content
generate_crontab() {
    local mode=$1
    
    if [[ "$mode" == "add" ]]; then
        # Add header comment
        echo "# AI Employee Watchers - Auto-generated by setup_cron.sh"
        echo "# Generated on: $(date)"
        echo ""
        
        # Add all entries
        for entry in "${CRON_ENTRIES[@]}"; do
            echo "$entry"
        done
        
        echo ""
        echo "# End of AI Employee cron entries"
    fi
}

# Main logic
if [[ "$REMOVE" == true ]]; then
    echo "Removing AI Employee cron entries..."
    
    if [[ "$DRY_RUN" == true ]]; then
        echo "[DRY RUN] Would remove the following entries:"
        for entry in "${CRON_ENTRIES[@]}"; do
            echo "  - $entry"
        done
    else
        # Remove entries that match our pattern
        NEW_CRONTAB=$(echo "$CURRENT_CRONTAB" | grep -v "AI Employee" | grep -v "$WATCHERS_DIR" | grep -v "claude --print" || true)
        echo "$NEW_CRONTAB" | $CRONTAB_CMD -
        echo "✓ Cron entries removed successfully"
    fi
else
    echo "Setting up AI Employee cron entries..."
    
    if [[ "$DRY_RUN" == true ]]; then
        echo "[DRY RUN] Would add the following entries:"
        generate_crontab "add"
        echo ""
        echo "Current crontab:"
        echo "$CURRENT_CRONTAB"
    else
        # Check if already exists
        if echo "$CURRENT_CRONTAB" | grep -q "AI Employee"; then
            echo "Warning: AI Employee cron entries already exist!"
            read -p "Do you want to replace them? (y/n): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                echo "Aborted."
                exit 0
            fi
            # Remove old entries first
            CURRENT_CRONTAB=$(echo "$CURRENT_CRONTAB" | grep -v "AI Employee" | grep -v "$WATCHERS_DIR" | grep -v "claude --print" || true)
        fi
        
        # Add new entries
        NEW_CRONTAB=$(generate_crontab "add")
        
        # Combine with existing (non-AI) entries
        if [[ -n "$CURRENT_CRONTAB" ]]; then
            FULL_CRONTAB="$CURRENT_CRONTAB"$'\n\n'"$NEW_CRONTAB"
        else
            FULL_CRONTAB="$NEW_CRONTAB"
        fi
        
        # Install crontab
        echo "$FULL_CRONTAB" | $CRONTAB_CMD -
        
        echo "✓ Cron entries added successfully!"
        echo ""
        echo "Scheduled tasks:"
        echo "  • Gmail watcher: Every 2 minutes"
        echo "  • WhatsApp watcher: Every 5 minutes"
        echo "  • LinkedIn watcher: Every 15 minutes"
        echo "  • Reasoning loop: Every 10 minutes"
        echo "  • LinkedIn posts: Mon/Wed/Fri at 9 AM"
        echo "  • Dashboard refresh: Every hour"
        echo "  • Approval expiry: Every 6 hours"
        echo "  • Orchestrator: Every minute"
        echo ""
        echo "Logs will be written to: $LOG_DIR/"
        echo ""
        echo "To view cron logs: tail -f $LOG_DIR/cron_*.log"
        echo "To remove cron entries: $0 --remove"
    fi
fi
